environment:
  matrix:
    - nodejs_version: "8"
      JSDOC_VERSION: <3.6

    - nodejs_version: ""
      JSDOC_VERSION: >=3.6

    - nodejs_version: ""
      JSDOC_VERSION: <3.6

cache:
  - node_modules
  - example/node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.npm'
  - '%USERPROFILE%\.cache'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
  - yarn install --frozen-lockfile
  - yarn add --save-dev jsdoc@$env:JSDOC_VERSION
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER) { yarn cypress install }
  - cd example
  - yarn install --frozen-lockfile
  - yarn add --save-dev jsdoc@$env:JSDOC_VERSION
  - cd ..

build: off

before_test:
  - cd example
  - yarn docs
  - yarn docs:docstrap
  - yarn docs:minami
  - yarn docs:tui
  - cd ..

test_script:
  - yarn lint
  - yarn test -i
  - yarn codecov
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER) { yarn cypress run --record }
