environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: ""

cache:
  - node_modules
  - example/node_modules
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
  - yarn install --frozen-lockfile
  - yarn cypress install
  - cd example
  - yarn install --frozen-lockfile
  - cd ..

build: off

before_test:
  - cd example
  - yarn docs
  - yarn docs:docstrap
  - yarn docs:minami
  - yarn docs:tui
  - cd ..

test_script:
  - yarn lint
  - yarn test -i
  - yarn codecov
  - yarn cypress run --config watchForFileChanges=false --record
