dist: trusty

language: node_js
node_js:
  - "8"
  - "node"

cache:
  yarn: true
  directories:
    - node_modules
    - example/node_modules
    - ~/.npm
    - ~/.cache

before_install:
  - npm i -g yarn

install:
  - yarn install --frozen-lockfile
  - cd example && yarn install --frozen-lockfile && cd ..
  - yarn cypress install

before_script:
  - cd example
  - yarn docs
  - yarn docs:docstrap
  - yarn docs:minami
  - yarn docs:tui
  - cd ..

script:
  - yarn lint
  - yarn test -i && yarn codecov
  - yarn cypress run --config watchForFileChanges=false --record
