language: node_js
node_js:
  - "8"
  - "7"
  - "6"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn
  - cd example && yarn && cd ..

before_script:
  - cd example
  - yarn jsdoc -d docs -c jsdoc.json
  - yarn jsdoc -d docs-docstrap -c jsdoc.json -t ./node_modules/ink-docstrap/template
  - yarn jsdoc -d docs-minami -c jsdoc.json -t ./node_modules/minami
  - yarn jsdoc -d docs-pixi -c jsdoc.json -t ./node_modules/@pixi/jsdoc-template
  - yarn jsdoc -d docs-tui -c jsdoc.json -t ./node_modules/tui-jsdoc-template

script:
  - yarn lint
  - yarn test

after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
