dist: trusty

language: node_js
node_js:
  - "8"
  - "node"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

cache:
  yarn: true
  directories:
    - node_modules
    - example/node_modules
    - ~/.npm
    - ~/.cache

before_install:
  - npm i -g yarn

install:
  - yarn install --frozen-lockfile
  - (cd example; yarn install --frozen-lockfile)
  - if [[ "${TRAVIS_EVENT_TYPE}" = pull_request ]]; then yarn cypress install; fi

before_script:
  - cd example
  - yarn docs
  - yarn docs:docstrap
  - yarn docs:minami
  - yarn docs:tui
  - cd ..

script:
  - yarn lint
  - yarn test -i && yarn codecov
  - if [[ "${TRAVIS_EVENT_TYPE}" = pull_request ]]; then yarn cypress run --config --record; fi

jobs:
  include:
    - stage: Release
      if: branch = master AND type = push
      node_js: node
      script: yarn semantic-release

