sudo: false
dist: trusty

language: node_js
node_js:
  - "6"
  - "8"
  - "9"
  - "10"

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache

before_install:
  - npm i -g yarn

install:
  - yarn
  - cd example && yarn && cd ..
  - yarn cypress install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd example
  - yarn jsdoc -d docs -c jsdoc.json
  - yarn jsdoc -d docs-docstrap -c jsdoc.json -t ./node_modules/ink-docstrap/template
  - yarn jsdoc -d docs-minami -c jsdoc.json -t ./node_modules/minami
  - yarn jsdoc -d docs-tui -c jsdoc.json -t ./node_modules/tui-jsdoc-template
  - cd ..

script:
  - yarn lint
  - yarn test -i
  - yarn cypress run --browser chrome --config watchForFileChanges=false

after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
