name: Node CI

on:
    pull_request:
        branches:
            - '*'

jobs:
    ci:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [10.x, 12.x, 14.x]
                include:
                    -   os: windows-latest
                        node: 12.x

        steps:
            -   name: Set git to use LF
                run: |
                    git config --global core.autocrlf false
                    git config --global core.eol lf
                if: matrix.os == 'windows-latest'

            -   uses: actions/checkout@v2

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: Get yarn cache directory
                id: yarn-cache
                run: echo "::set-output name=dir::$(yarn cache dir)"

            -   name: Restore yarn cache (if available)
                uses: actions/cache@v1
                with:
                    path: ${{ steps.yarn-cache.outputs.dir }}
                    key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-yarn-

            -   run: yarn install --frozen-lockfile

            -   run: |
                    cd example
                    yarn install --frozen-lockfile
                    yarn docs
                    yarn docs:docstrap
                    yarn docs:minami
                    yarn docs:tui
                    cd ..

            -   run: yarn lint

            -   run: yarn test -i && npx codecov
