name: Release

on:
    push:
        branches:
            - master

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Install Node.js
                uses: actions/setup-node@v1
                with:
                    node-version: 12.x

            -   run: yarn install --frozen-lockfile

            -   run: yarn semantic-release
                env:
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
